steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: restore_cache
    waitFor: ['-']
    args:
    - '--bucket=gs://nicktouchette-project-cache/'
    - '--key=package-$( checksum package.json )'
  - name: node
    id: build
    entrypoint: yarn
    args: ['${_GATSBY}', 'build', '--prefix-paths']
  # - name: node
  #   id: build
  #   entrypoint: yarn
  #   args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', 'public/', 'gs://gatsby-blog-example']

substitutions:
  _GATSBY: node_modules/gatsby/dist/bin/gatsby